@baseUrl = http://localhost:3000

# Notices
# @name Create
POST {{baseUrl}}/notices HTTP/1.1
Content-Type: application/json

{
  "title": "Alerta",
  "description": "Esse é um alerta grave",
  "priority": "Alta",
  "status": "Ativo",
  "createdBy":"096e58a7-e89b-4665-af3c-2acadbcf89a0"
}

###
# @name GetAll
GET {{baseUrl}}/notices HTTP/1.1
Content-Type: application/json

###
# @name GetOne
GET {{baseUrl}}/notices/a618da11-88d0-44db-b2bd-28397e194c07 HTTP/1.1
Content-Type: application/json

###
# @name Update
PATCH {{baseUrl}}/notices/3b9a95aa-da9c-4eff-a3dd-f22a7438ecc3 HTTP/1.1
Content-Type: application/json

{
  "title": "Alerta modificado",
  "description": "Esse é um alerta grave",
  "priority": "Alta",
  "status": "Ativo"
}

###
# @name Delete
DELETE  {{baseUrl}}/notices/a93e73c0-693d-417c-9936-b7e7b2e82a8d HTTP/1.1
Content-Type: application/json










