@baseUrl = http://localhost:3000

# Residents
# @name Create
POST {{baseUrl}}/residents HTTP/1.1
Content-Type: application/json

{
  "name": "Emerson Batista",
  "apartment": "11",
  "building":"Bloco F",
  "email": "emerson.bl.5476+688@gmail.com",
  "password":"142743Co@#$7*",
  "phone":"5599985203020"
}

###
# @name GetAll
GET {{baseUrl}}/residents HTTP/1.1
Content-Type: application/json

###
# @name GetOne
GET {{baseUrl}}/residents/a51f9beb-527e-4b15-bc37-900c017aea8e HTTP/1.1
Content-Type: application/json

###
# @name Update
PATCH {{baseUrl}}/residents/7acb87ca-b117-4e94-8630-d7773068b7ab HTTP/1.1
Content-Type: application/json

{ "password":"142743Co@#$7*",
  "phone":"5599985203024",
  "email": "emerson.bl.876+5@gmail.com"}

###
# @name Delete
DELETE  {{baseUrl}}/residents/d27ae9e3-b639-4fdf-b502-190942807e22 HTTP/1.1
Content-Type: application/json

###
# @name DeleteAll
DELETE  {{baseUrl}}/residents/ HTTP/1.1
Content-Type: application/json










